version: 1.2
workflows:
 - name: GBS_Identification_and_Typing
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_gbs_id_and_typing.wdl
   testParameterFiles:
    - /files/empty.json
 - name: BLAST_virulence
   subclass: WDL
   primaryDescriptorPath: /tasks/task_blast_virulence.wdl
   testParameterFiles:
    - /files/empty.json